import { useState, useEffect } from 'react';
import { User, View, ForumTopic, ForumPost, Room } from '../types';
import { LogOut, Settings, Shield, Award, LayoutGrid, ArrowRight, Edit3, Heart, X, Search, LifeBuoy, Trash2, Clock, Lock, Globe, Users, MessageSquare, Calendar, ChevronDown, ChevronUp, PenSquare } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { getAvatarById } from '../data/avatars';
import AvatarModal from '../components/AvatarModal';
import { apiService } from '../services/api';

interface Props {
  user: User | null;
  navigate: (view: View, state?: any) => void;
  onLogout: () => void;
  onUpdateUser?: (updated: User) => void;
  topics: ForumTopic[];
  onUpdateTopics: (updatedTopics: ForumTopic[]) => void;
}

export default function Profile({ user, navigate, onLogout, onUpdateUser, topics, onUpdateTopics }: Props) {
  const [isAvatarModalOpen, setIsAvatarModalOpen] = useState(false);
  const [isShowingLegalText, setIsShowingLegalText] = useState(false);

  const avatar = getAvatarById(user?.avatarId || '');

  // --- Profile Activity State & Constants ---
  const EDIT_TIMEOUT_O_MS = 5 * 60 * 1000; // 5 minutes edit window

  // Accordion UI states
  const [isForumActivityOpen, setIsForumActivityOpen] = useState(false);
  const [isRoomsActivityOpen, setIsRoomsActivityOpen] = useState(false);

  // Forum Tab
  const [forumActiveTab, setForumActiveTab] = useState<'topics' | 'comments'>('topics');

  // Custom rooms generated by the premium user
  const [customRooms, setCustomRooms] = useState<Room[]>([]);

  useEffect(() => {
    const USE_API = (import.meta as any).env?.VITE_USE_API === 'true';
    if (USE_API && user) {
      apiService.rooms.fetchAll()
        .then((rooms) => {
          const filtered = rooms.filter(r =>
            r.ownerId === user.id ||
            r.invitedBy === (user.nickname || user.name) ||
            (r.isPremiumRoom && r.invitedBy === (user.nickname || user.name))
          );
          setCustomRooms(filtered);
        })
        .catch(err => {
          console.warn('[API Profile Rooms] Fetch failed:', err);
        });
    } else {
      const saved = localStorage.getItem('recomecar_custom_rooms');
      if (saved) {
        try {
          const parsed = JSON.parse(saved);
          setCustomRooms(parsed.filter((r: any) => r.invitedBy === (user?.nickname || user?.name) || (r.isPremiumRoom && r.invitedBy === (user?.nickname || user?.name))));
        } catch (e) {
          console.error(e);
        }
      }
    }
  }, [user]);

  // Modal / Editing states
  const [editingPost, setEditingPost] = useState<{ topicId: string; post: ForumPost; title: string } | null>(null);
  const [editPostContent, setEditPostContent] = useState('');

  const [topicToDelete, setTopicToDelete] = useState<ForumTopic | null>(null);

  const [editingRoom, setEditingRoom] = useState<Room | null>(null);
  const [editRoomName, setEditRoomName] = useState('');
  const [editRoomDesc, setEditRoomDesc] = useState('');
  const [editRoomType, setEditRoomType] = useState<'public' | 'vip'>('public');

  // Controlled list limits to prevent infinite downward growth
  const [visibleTopicsCount, setVisibleTopicsCount] = useState(3);
  const [visibleCommentsCount, setVisibleCommentsCount] = useState(3);
  const [visibleRoomsCount, setVisibleRoomsCount] = useState(3);

  // Derive my topics
  const myTopics = topics.filter(t => t.authorName === (user?.nickname || user?.name) || t.authorName === 'Você');

  // Derive my comment replies
  const myComments: { topic: ForumTopic; post: ForumPost }[] = [];
  topics.forEach(t => {
    t.posts.forEach((p, idx) => {
      if (idx > 0 && (p.authorName === (user?.nickname || user?.name) || p.authorName === 'Você')) {
        myComments.push({ topic: t, post: p });
      }
    });
  });

  const isEditable = (timestamp: number) => {
    return (Date.now() - timestamp) < EDIT_TIMEOUT_O_MS;
  };

  const getRemainingEditTime = (timestamp: number) => {
    const remaining = EDIT_TIMEOUT_O_MS - (Date.now() - timestamp);
    if (remaining <= 0) return '';
    const mins = Math.floor(remaining / 60000);
    const secs = Math.floor((remaining % 60000) / 1000);
    return `${mins}m ${secs}s`;
  };

  // --- Forums Handlers ---
  const handleSavePostEdit = () => {
    if (!editingPost || !editPostContent.trim()) return;
    const { topicId, post } = editingPost;

    const updated = topics.map(t => {
      if (t.id === topicId) {
        return {
          ...t,
          posts: t.posts.map(p => {
            if (p.id === post.id) {
              return {
                ...p,
                content: editPostContent.trim()
              };
            }
            return p;
          })
        };
      }
      return t;
    });

    onUpdateTopics(updated);
    setEditingPost(null);
  };

  const handleDeleteComment = (topicId: string, postId: string) => {
    const updated = topics.map(t => {
      if (t.id === topicId) {
        return {
          ...t,
          posts: t.posts.map(p => {
            if (p.id === postId) {
              return {
                ...p,
                content: '[Este comentário foi apagado pelo autor]',
                isDeleted: true
              };
            }
            return p;
          })
        };
      }
      return t;
    });

    onUpdateTopics(updated);
  };

  const handleScheduleTopicDeletion = (topicId: string) => {
    const updated = topics.map(t => {
      if (t.id === topicId) {
        return {
          ...t,
          scheduledDeletionTime: Date.now() + 24 * 60 * 60 * 1000
        };
      }
      return t;
    });
    onUpdateTopics(updated);
    setTopicToDelete(null);
  };

  const handleImmediateTopicDeletion = (topicId: string) => {
    const updated = topics.filter(t => t.id !== topicId);
    onUpdateTopics(updated);
    setTopicToDelete(null);
  };

  // --- Rooms Handlers ---
  const handleSaveRoomEdit = () => {
    if (!editingRoom || !editRoomName.trim() || !editRoomDesc.trim()) return;
    const USE_API = (import.meta as any).env?.VITE_USE_API === 'true';

    if (USE_API) {
      apiService.rooms.update(editingRoom.id, {
        name: editRoomName.trim(),
        description: editRoomDesc.trim(),
        type: editRoomType.toUpperCase() as any
      })
        .then((updated) => {
          setCustomRooms(prev => prev.map(r => r.id === updated.id ? { ...r, ...updated } : r));
          setEditingRoom(null);
        })
        .catch(err => {
          alert('Erro ao salvar as edições da sala no servidor.');
          console.error(err);
        });
    } else {
      const saved = localStorage.getItem('recomecar_custom_rooms');
      let allRooms: Room[] = [];
      if (saved) {
        try {
          allRooms = JSON.parse(saved);
        } catch (e) {
          console.error(e);
        }
      }

      const updatedRooms = allRooms.map(r => {
        if (r.id === editingRoom.id) {
          return {
            ...r,
            name: editRoomName.trim(),
            description: editRoomDesc.trim(),
            type: editRoomType
          };
        }
        return r;
      });

      localStorage.setItem('recomecar_custom_rooms', JSON.stringify(updatedRooms));
      setCustomRooms(updatedRooms.filter(r => r.invitedBy === (user?.nickname || user?.name) || (r.isPremiumRoom && r.invitedBy === (user?.nickname || user?.name))));
      setEditingRoom(null);
    }
  };

  const handleDeleteRoom = (roomId: string) => {
    const USE_API = (import.meta as any).env?.VITE_USE_API === 'true';

    if (USE_API) {
      apiService.rooms.delete(roomId)
        .then(() => {
          setCustomRooms(prev => prev.filter(r => r.id !== roomId));
        })
        .catch(err => {
          alert('Erro ao excluir a sala no servidor.');
          console.error(err);
        });
    } else {
      const saved = localStorage.getItem('recomecar_custom_rooms');
      let allRooms: Room[] = [];
      if (saved) {
        try {
          allRooms = JSON.parse(saved);
        } catch (e) {
          console.error(e);
        }
      }

      const updatedRooms = allRooms.filter(r => r.id !== roomId);
      localStorage.setItem('recomecar_custom_rooms', JSON.stringify(updatedRooms));
      setCustomRooms(updatedRooms.filter(r => r.invitedBy === (user?.nickname || user?.name) || (r.isPremiumRoom && r.invitedBy === (user?.nickname || user?.name))));
    }
  };

  const handleSelectAvatar = (selectedAvatar: any) => {
    if (user && onUpdateUser) {
      onUpdateUser({
        ...user,
        avatarId: selectedAvatar.id
      });
    }
  };

  const handleRemoveAngel = (angelId: string) => {
    if (user && onUpdateUser) {
      const updatedAngels = (user.supportAngels || []).filter(a => a.id !== angelId);
      onUpdateUser({
        ...user,
        supportAngels: updatedAngels
      });
    }
  };

  const [searchQuery, setSearchQuery] = useState('');

  const supportAngels = user?.supportAngels || [];

  const filteredAngels = supportAngels.filter(angel =>
    angel.name.toLowerCase().includes(searchQuery.trim().toLowerCase())
  );

  return (
    <div className="h-full w-full flex flex-col bg-[#020410] overflow-y-auto no-scrollbar">
      <div className="bg-[#0a0f1f]/90 border-b border-white/5 px-6 pt-16 pb-10 rounded-b-[2rem] shadow-neon-purple shadow-sm">
        <div className="flex flex-col items-center space-y-4">
          <button
            onClick={() => setIsAvatarModalOpen(true)}
            className="w-24 h-24 rounded-full bg-purple-500/10 flex items-center justify-center border-2 border-purple-500/30 shadow-neon-purple shadow-xl overflow-hidden relative group active:scale-95 transition-all outline-none cursor-pointer"
            title="Escolher avatar"
          >
            <span className="text-4xl">{avatar?.emoji || '👋'}</span>
            <div className="absolute inset-0 bg-purple-500/30 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
              <Edit3 size={18} className="text-white" />
            </div>
          </button>
          <div className="text-center">
            <h2 className="text-2xl font-display font-semibold text-white">{user?.nickname || user?.name || 'Viajante'}</h2>
            <p className="text-gray-500 text-sm italic">Cuidando de si mesmo um dia de cada vez.</p>
            <button
              onClick={() => setIsAvatarModalOpen(true)}
              className="mt-2 text-xs text-purple-400 font-bold tracking-tight hover:underline focus:outline-none cursor-pointer"
            >
              Alterar avatar
            </button>
          </div>
        </div>
      </div>


      <div className="p-6 space-y-6">
        {/* Meus Anjos de Apoio Profile Showcase */}
        <div className="space-y-3">
          <div className="flex items-center justify-between px-2">
            <h3 className="text-xs font-medium uppercase tracking-widest text-gray-500">Meus Anjos de Apoio</h3>
            <span className="text-[10px] bg-purple-500/10 text-purple-400 font-bold px-2 py-0.5 rounded-full border border-purple-500/20">
              {supportAngels.length} Ativo(s)
            </span>
          </div>

          <div className="bg-[#0a0f1f]/60 rounded-3xl p-5 border border-white/5 overflow-hidden">
            {/* Elegant Search Bar displayed only when user has more than 4 angels to maintain pristine UX */}
            {supportAngels.length > 4 && (
              <div className="relative mb-4 flex items-center bg-[#12182b] rounded-2xl px-3.5 py-2.5 border border-white/5 transition-all focus-within:border-purple-500/30">
                <Search size={14} className="text-gray-500 shrink-0 mr-2" />
                <input
                  type="text"
                  placeholder="Buscar anjo pelo nome..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="bg-transparent text-xs text-white placeholder-gray-500 outline-none w-full font-medium"
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery('')}
                    className="p-1 rounded-full text-gray-400 hover:bg-white/10 hover:text-white active:scale-95 transition-all ml-1 outline-none cursor-pointer"
                  >
                    <X size={12} />
                  </button>
                )}
              </div>
            )}

            {supportAngels.length === 0 ? (
              <div className="text-center py-4 space-y-2">
                <div className="w-10 h-10 rounded-full bg-purple-500/10 text-purple-400 flex items-center justify-center mx-auto">
                  <Heart size={20} className="fill-purple-500/20 animate-pulse" />
                </div>
                <p className="text-xs text-gray-400 font-light leading-relaxed max-w-[240px] mx-auto">
                  Toque no avatar de outros membros no fórum ou na sala para adicioná-los como seus <strong className="text-purple-400 font-semibold">Anjos de Apoio</strong>.
                </p>
              </div>
            ) : filteredAngels.length === 0 ? (
              <div className="text-center py-4 space-y-2">
                <p className="text-xs text-gray-400 font-medium">Nenhum anjo com "{searchQuery}" foi encontrado.</p>
                <button
                  onClick={() => setSearchQuery('')}
                  className="text-[10px] text-purple-400 font-bold underline hover:text-purple-300 active:scale-95 transition-all outline-none cursor-pointer"
                >
                  Limpar pesquisa
                </button>
              </div>
            ) : (
              <div className="flex items-center space-x-3 overflow-x-auto pb-1 pt-1.5 no-scrollbar -mx-2 px-2 snap-x snap-mandatory">
                {filteredAngels.map((angel) => {
                  const angelAvatar = getAvatarById(angel.avatarId);
                  return (
                    <motion.div
                      key={angel.id}
                      initial={{ scale: 0.9, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      className="snap-start shrink-0 flex flex-col items-center bg-white/5 p-3 rounded-2xl border border-white/5 min-w-[80px] relative group text-center"
                    >
                      <div className="w-12 h-12 rounded-full bg-white/5 flex items-center justify-center text-2.5xl shadow-xs border border-white/5 relative">
                        {angelAvatar?.emoji || '👤'}
                        <span className="absolute bottom-0 right-0 w-2.5 h-2.5 bg-emerald-500 rounded-full border border-[#020410] animate-pulse" />
                      </div>
                      <span className="text-[10px] font-bold text-white truncate w-14 mt-2 font-display leading-tight">{angel.name}</span>

                      <button
                        onClick={() => handleRemoveAngel(angel.id)}
                        className="absolute -top-1.5 -right-1.5 w-5 h-5 bg-[#1a0c0e] border border-red-500/30 hover:bg-red-550 text-red-400 hover:text-white rounded-full flex items-center justify-center shadow-xs active:scale-90 transition-all outline-none cursor-pointer"
                        title="Remover anjo"
                      >
                        <X size={10} />
                      </button>
                    </motion.div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Minha Atividade no Fórum */}
        <div className="space-y-3" id="forum-activity-panel">
          <button
            onClick={() => setIsForumActivityOpen(!isForumActivityOpen)}
            className="w-full flex items-center justify-between px-2 text-left outline-none group cursor-pointer"
          >
            <h3 className="text-xs font-semibold uppercase tracking-widest text-gray-500 group-hover:text-gray-400 transition-colors">Minha Atividade no Fórum</h3>
            <div className="flex items-center space-x-2 text-xs text-purple-400 font-bold">
              <span>{myTopics.length} tópico(s) e {myComments.length} coment.</span>
              {isForumActivityOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
            </div>
          </button>

          {isForumActivityOpen && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              className="bg-[#0a0f1f]/60 rounded-3xl p-5 border border-white/5 space-y-4"
            >
              {/* Toggles */}
              <div className="flex bg-[#12182b] p-1 rounded-2xl border border-white/5">
                <button
                  type="button"
                  onClick={() => setForumActiveTab('topics')}
                  className={`flex-1 py-2 text-center text-xs font-bold rounded-xl transition-all cursor-pointer ${forumActiveTab === 'topics'
                    ? 'bg-[#0a0f1f] text-white border border-white/5 shadow-sm'
                    : 'text-gray-500 hover:text-gray-400'
                    }`}
                >
                  Meus Tópicos ({myTopics.length})
                </button>
                <button
                  type="button"
                  onClick={() => setForumActiveTab('comments')}
                  className={`flex-1 py-2 text-center text-xs font-bold rounded-xl transition-all cursor-pointer ${forumActiveTab === 'comments'
                    ? 'bg-[#0a0f1f] text-white border border-white/5 shadow-sm'
                    : 'text-gray-500 hover:text-gray-400'
                    }`}
                >
                  Meus Comentários ({myComments.length})
                </button>
              </div>

              {/* Topics List */}
              {forumActiveTab === 'topics' && (
                <div className="space-y-2.5 max-h-80 overflow-y-auto pr-1 no-scrollbar flex flex-col">
                  {myTopics.length === 0 ? (
                    <p className="text-xs text-gray-500 italic text-center py-4">Você ainda não criou nenhum tópico de discussão.</p>
                  ) : (
                    <>
                      {myTopics.slice(0, visibleTopicsCount).map(topic => {
                        const firstPost = topic.posts[0];
                        const canEditTopic = firstPost && isEditable(firstPost.timestamp);
                        const isDeletedScheduled = !!topic.scheduledDeletionTime;

                        return (
                          <div key={topic.id} className="p-3 bg-[#12182b]/55 hover:bg-[#12182b]/80 rounded-2xl border border-white/5 space-y-2 transition-all">
                            <div className="flex justify-between items-start gap-2">
                              <button
                                type="button"
                                onClick={() => navigate('topic-detail', { topicId: topic.id })}
                                className="text-xs font-bold text-white hover:text-purple-400 text-left leading-snug flex-1 transition-colors cursor-pointer"
                              >
                                💬 {topic.title}
                              </button>
                              <span className="text-[9px] font-mono px-2 py-0.5 rounded-full bg-purple-500/10 text-purple-400 border border-purple-500/20 shrink-0 font-bold">
                                {topic.category}
                              </span>
                            </div>

                            {isDeletedScheduled && (
                              <p className="text-[10px] text-amber-400 flex items-center gap-1 font-medium bg-amber-500/5 px-2 py-1 rounded-lg border border-amber-500/10">
                                ⚠️ Exclusão agendada em 24h
                              </p>
                            )}

                            <div className="flex justify-between items-center pt-1 border-t border-white/5">
                              <span className="text-[9px] text-gray-550 flex items-center gap-1">
                                <Calendar size={10} />
                                {new Date(topic.lastUpdate).toLocaleDateString('pt-BR')}
                              </span>
                              <div className="flex items-center space-x-1.5">
                                {canEditTopic && firstPost ? (
                                  <button
                                    type="button"
                                    onClick={() => {
                                      setEditingPost({ topicId: topic.id, post: firstPost, title: topic.title });
                                      setEditPostContent(firstPost.content);
                                    }}
                                    className="text-[10px] text-purple-400 font-bold hover:underline py-1 px-2 bg-purple-500/10 border border-purple-500/20 rounded-lg flex items-center gap-1 active:scale-95 transition-all outline-none cursor-pointer"
                                  >
                                    <PenSquare size={10} /> Editar
                                  </button>
                                ) : firstPost ? (
                                  <span className="text-[9px] text-gray-500 flex items-center gap-0.5" title="Tempo de edição esgotado">
                                    <Clock size={10} /> Expirado
                                  </span>
                                ) : null}

                                <button
                                  type="button"
                                  onClick={() => setTopicToDelete(topic)}
                                  className={`text-[10px] font-bold py-1 px-2 rounded-lg flex items-center gap-1 active:scale-95 transition-all outline-none cursor-pointer ${isDeletedScheduled
                                    ? 'text-amber-400 bg-amber-500/10 border border-amber-500/20 hover:bg-amber-500/15'
                                    : 'text-red-400 bg-red-500/10 hover:bg-red-500/15 border border-red-500/20'
                                    }`}
                                >
                                  <Trash2 size={10} /> {isDeletedScheduled ? 'Cancelar Excl.' : 'Excluir'}
                                </button>
                              </div>
                            </div>
                          </div>
                        );
                      })}

                      {myTopics.length > visibleTopicsCount && (
                        <button
                          type="button"
                          onClick={() => setVisibleTopicsCount(prev => prev + 3)}
                          className="w-full text-center py-2.5 mt-1 text-[10px] font-bold text-purple-400 hover:text-purple-300 bg-purple-500/5 hover:bg-purple-500/10 rounded-xl transition-all outline-none border border-purple-500/10 cursor-pointer"
                        >
                          Carregar mais tópicos (+3)
                        </button>
                      )}
                    </>
                  )}
                </div>
              )}

              {/* Comments (Replies) List */}
              {forumActiveTab === 'comments' && (
                <div className="space-y-2.5 max-h-80 overflow-y-auto pr-1 no-scrollbar flex flex-col">
                  {myComments.length === 0 ? (
                    <p className="text-xs text-gray-550 italic text-center py-4">Você ainda não comentou em nenhum tópico.</p>
                  ) : (
                    <>
                      {myComments.slice(0, visibleCommentsCount).map(({ topic, post }) => {
                        const canEditComment = isEditable(post.timestamp) && !post.isDeleted;
                        return (
                          <div key={post.id} className="p-3 bg-[#12182b]/55 hover:bg-[#12182b]/80 rounded-2xl border border-white/5 space-y-2 transition-all">
                            <div className="flex justify-between items-start gap-2">
                              <button
                                type="button"
                                onClick={() => navigate('topic-detail', { topicId: topic.id, postId: post.id })}
                                className="text-[10px] text-gray-400 hover:text-purple-400 text-left transition-colors truncate flex-1 cursor-pointer"
                              >
                                Em: <strong className="text-white font-bold text-xs">{topic.title}</strong>
                              </button>
                            </div>

                            <p className={`text-[11.5px] leading-relaxed break-words ${post.isDeleted ? 'text-gray-550 italic' : 'text-white'}`}>
                              {post.isDeleted ? '🚫 Comentário removido por você' : post.content}
                            </p>

                            <div className="flex justify-between items-center pt-1 border-t border-white/5">
                              <span className="text-[9px] text-gray-550 flex items-center gap-1">
                                <Calendar size={10} />
                                {new Date(post.timestamp).toLocaleDateString('pt-BR')}
                              </span>

                              {!post.isDeleted && (
                                <div className="flex items-center space-x-1.5">
                                  {canEditComment ? (
                                    <button
                                      type="button"
                                      onClick={() => {
                                        setEditingPost({ topicId: topic.id, post, title: topic.title });
                                        setEditPostContent(post.content);
                                      }}
                                      className="text-[10px] text-purple-400 font-bold hover:underline py-1 px-2 bg-purple-500/10 border border-purple-500/20 rounded-lg flex items-center gap-1 active:scale-95 transition-all outline-none cursor-pointer"
                                    >
                                      <PenSquare size={10} /> Editar
                                    </button>
                                  ) : (
                                    <span className="text-[9px] text-gray-500 flex items-center gap-0.5" title="Tempo de edição expirado">
                                      <Clock size={10} /> Expirado
                                    </span>
                                  )}

                                  <button
                                    type="button"
                                    onClick={() => handleDeleteComment(topic.id, post.id)}
                                    className="text-[10px] text-[#ff4a5a] font-bold py-1 px-2 bg-red-500/10 hover:bg-red-500/15 border border-red-500/20 rounded-lg flex items-center gap-1 active:scale-95 transition-all outline-none cursor-pointer"
                                  >
                                    <Trash2 size={10} /> Excluir
                                  </button>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      })}

                      {myComments.length > visibleCommentsCount && (
                        <button
                          type="button"
                          onClick={() => setVisibleCommentsCount(prev => prev + 3)}
                          className="w-full text-center py-2.5 mt-1 text-[10px] font-bold text-purple-400 hover:text-purple-300 bg-white/5 hover:bg-white/10 rounded-xl transition-all outline-none border border-white/5 cursor-pointer"
                        >
                          Carregar mais comentários (+3)
                        </button>
                      )}
                    </>
                  )}
                </div>
              )}

            </motion.div>
          )}
        </div>

        {/* Minhas Salas Personalizadas (Apenas Premium) */}
        {user?.plan === 'PREMIUM' && (
          <div className="space-y-3" id="premium-rooms-panel">
            <button
              onClick={() => setIsRoomsActivityOpen(!isRoomsActivityOpen)}
              className="w-full flex items-center justify-between px-2 text-left outline-none group cursor-pointer"
            >
              <h3 className="text-xs font-semibold uppercase tracking-widest text-cyan-400 group-hover:text-cyan-300 transition-colors shrink-0">Minhas Salas de Apoio</h3>
              <div className="flex items-center space-x-2 text-xs text-cyan-400 font-bold">
                <span>{customRooms.length} sala(s) criada(s)</span>
                {isRoomsActivityOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
              </div>
            </button>

            {isRoomsActivityOpen && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                className="bg-[#0a0f1f]/60 rounded-3xl p-5 border border-white/5 space-y-4"
              >
                {customRooms.length === 0 ? (
                  <div className="text-center py-5 space-y-2">
                    <p className="text-xs text-gray-400 font-light">Você ainda não criou nenhuma sala personalizada de apoio.</p>
                    <button
                      type="button"
                      onClick={() => navigate('rooms')}
                      className="text-[10.5px] bg-cyan-600 hover:bg-cyan-705 text-white font-bold px-3 py-1.5 rounded-full active:scale-95 transition-transform cursor-pointer"
                    >
                      Criar primeira sala ↗
                    </button>
                  </div>
                ) : (
                  <div className="space-y-3 max-h-80 overflow-y-auto pr-1 no-scrollbar flex flex-col">
                    {customRooms.slice(0, visibleRoomsCount).map(room => (
                      <div key={room.id} className="p-3.5 bg-[#12182b]/55 hover:bg-[#12182b]/80 border border-white/5 rounded-2xl transition-all space-y-2">
                        <div className="flex items-center justify-between">
                          <span className="text-xs font-bold text-white truncate leading-snug">
                            🛡️ {room.name}
                          </span>
                          <span className={`text-[8.5px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${room.type === 'vip'
                            ? 'bg-amber-500/10 text-amber-400 border-amber-500/20'
                            : 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
                            }`}>
                            {room.type === 'vip' ? '🔒 Privada (Apenas com Convite)' : '🌐 Pública'}
                          </span>
                        </div>

                        <p className="text-[10.5px] text-gray-400 font-light leading-relaxed truncate">
                          {room.description || 'Sem descrição cadastrada.'}
                        </p>

                        <div className="flex items-center justify-between pt-2 border-t border-white/5">
                          <span className="text-[9px] text-gray-550 flex items-center gap-1">
                            <Users size={10} />
                            Criada por Você (Premium)
                          </span>

                          <div className="flex items-center space-x-1.5">
                            <button
                              type="button"
                              onClick={() => {
                                setEditingRoom(room);
                                setEditRoomName(room.name);
                                setEditRoomDesc(room.description || '');
                                setEditRoomType(room.type as 'public' | 'vip' || 'public');
                              }}
                              className="text-[10px] text-cyan-400 font-bold px-2 py-1 bg-cyan-500/10 border border-cyan-500/20 hover:underline rounded-lg flex items-center gap-1 active:scale-95 transition-all outline-none cursor-pointer"
                            >
                              Editar
                            </button>
                            <button
                              type="button"
                              onClick={() => {
                                if (confirm(`Deseja realmente excluir permanentemente a sala "${room.name}"?`)) {
                                  handleDeleteRoom(room.id);
                                }
                              }}
                              className="text-[10px] text-red-400 font-bold px-2 py-1 bg-red-500/10 hover:bg-red-500/15 border border-red-500/20 rounded-lg flex items-center gap-1 active:scale-95 transition-all outline-none cursor-pointer"
                            >
                              Excluir
                            </button>
                          </div>
                        </div>
                      </div>
                    ))}

                    {customRooms.length > visibleRoomsCount && (
                      <button
                        type="button"
                        onClick={() => setVisibleRoomsCount(prev => prev + 3)}
                        className="w-full text-center py-2.5 mt-1 text-[10px] font-bold text-cyan-400 hover:text-cyan-300 bg-white/5 hover:bg-white/10 rounded-xl transition-all outline-none border border-white/5 cursor-pointer"
                      >
                        Carregar mais salas (+3)
                      </button>
                    )}
                  </div>
                )}
              </motion.div>
            )}
          </div>
        )}

        <div className="space-y-3">
          <h3 className="text-xs font-medium uppercase tracking-widest text-gray-505 px-2">Bem-estar</h3>
          <div className="bg-[#0a0f1f]/60 rounded-3xl overflow-hidden border border-white/5">
            <button onClick={() => navigate('vip')} className="w-full px-6 py-5 flex items-center justify-between border-b border-white/5 hover:bg-white/5 active:bg-white/10 transition-all cursor-pointer">
              <div className="flex items-center space-x-4">
                <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center text-amber-400">
                  <Award size={22} />
                </div>
                <span className="font-medium text-white">Meu Plano</span>
              </div>
              <ArrowRight size={18} className="text-gray-500" />
            </button>
            <button className="w-full px-6 py-5 flex items-center justify-between border-b border-white/5 hover:bg-white/5 active:bg-white/10 transition-all cursor-pointer">
              <div className="flex items-center space-x-4">
                <div className="w-10 h-10 rounded-xl bg-cyan-500/10 flex items-center justify-center text-cyan-400">
                  <LayoutGrid size={22} />
                </div>
                <span className="font-medium text-white">Histórico Emocional</span>
              </div>
              <ArrowRight size={18} className="text-gray-550" />
            </button>
            <button className="w-full px-6 py-5 flex items-center justify-between border-b border-white/5 hover:bg-white/5 active:bg-white/10 transition-all cursor-pointer">
              <div className="flex items-center space-x-4">
                <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400">
                  <Shield size={22} />
                </div>
                <span className="font-medium text-white">Configurações de Privacidade</span>
              </div>
              <ArrowRight size={18} className="text-gray-550" />
            </button>
            <button onClick={() => navigate('support')} className="w-full px-6 py-5 flex items-center justify-between hover:bg-white/5 active:bg-white/10 transition-all cursor-pointer" id="btn-profile-support">
              <div className="flex items-center space-x-4">
                <div className="w-10 h-10 rounded-xl bg-purple-500/10 flex items-center justify-center text-purple-400">
                  <LifeBuoy size={22} />
                </div>
                <span className="font-medium text-white">Suporte & Central de Ajuda</span>
              </div>
              <ArrowRight size={18} className="text-gray-550" />
            </button>
          </div>
        </div>

        <div className="space-y-3" id="legal-terms-section">
          <h3 className="text-xs font-medium uppercase tracking-widest text-gray-500 px-2">Segurança & Termos Legais</h3>
          <div className="bg-[#0a0f1f]/60 rounded-3xl p-5 border border-white/5 space-y-4">
            <div className="flex items-start space-x-3.5">
              <div className="w-10 h-10 rounded-xl bg-purple-500/10 flex items-center justify-center text-purple-400 shrink-0">
                <Shield size={22} className="animate-pulse" />
              </div>
              <div className="flex-1 min-w-0">
                <span className="text-xs font-bold text-white block">Termo de Consentimento</span>
                <p className="text-[11px] text-gray-500 leading-tight mt-0.5 font-light">Assinado eletronicamente e irrevogável.</p>
              </div>
              <span className="text-[10px] bg-emerald-500/10 text-emerald-400 font-bold px-2 py-0.5 rounded-full border border-emerald-500/20 flex items-center space-x-1 shrink-0">
                <span>🔒 Lock</span>
              </span>
            </div>

            {user?.termsAccepted ? (
              <div className="bg-[#12182b] rounded-2xl p-3.5 space-y-2 border border-white/5 text-[11px]">
                <div className="flex justify-between text-gray-400">
                  <span>Signatário:</span>
                  <strong className="text-white font-bold">{user.nickname || user.name}</strong>
                </div>
                <div className="flex justify-between text-gray-400">
                  <span>Data de Aceito:</span>
                  <strong className="text-white font-bold">
                    {user.termsAcceptedAt ? new Date(user.termsAcceptedAt).toLocaleString('pt-BR') : 'Gravado'}
                  </strong>
                </div>
                <div className="flex justify-between text-gray-400">
                  <span>Versão do Termo:</span>
                  <strong className="text-white font-mono font-bold">{user.termsVersion || '1.0.0-PRO-SAFE'}</strong>
                </div>
                <div className="flex justify-between text-gray-400">
                  <span>Status Regulatório:</span>
                  <span className="text-emerald-400 font-bold">Ativo & Auditado ✔</span>
                </div>

                <div className="grid grid-cols-2 gap-2 mt-2">
                  <button
                    onClick={() => setIsShowingLegalText(!isShowingLegalText)}
                    className="py-2.5 bg-white/5 hover:bg-white/10 text-white text-[10.5px] font-bold rounded-xl transition-all cursor-pointer flex items-center justify-center space-x-1 outline-none border border-white/5"
                    id="btn-toggle-terms"
                  >
                    <span>{isShowingLegalText ? 'Esconder Termo ▲' : 'Ler Termo Rápido ▼'}</span>
                  </button>
                  <button
                    onClick={() => navigate('privacy-policy')}
                    className="py-2.5 bg-purple-500/10 hover:bg-purple-500/15 text-purple-400 text-[10.5px] font-bold rounded-xl transition-all cursor-pointer flex items-center justify-center space-x-1 outline-none border border-purple-500/20"
                    id="btn-go-privacy-policy"
                  >
                    <span>Políticas / LGPD ↗</span>
                  </button>
                </div>

                {isShowingLegalText && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    className="mt-3 p-3 bg-[#12182b] rounded-xl border border-white/5 max-h-48 overflow-y-auto space-y-2 text-[10px] text-gray-400 leading-normal scrollbar-thin"
                    id="full-legal-text-container"
                  >
                    <p className="font-bold text-white uppercase tracking-wide">TERMO DE RESPONSABILIDADE CIVIL E ISENÇÃO DE SUPORTE MÉDICO-CLÍNICO (V1.0.0-PRO-SAFE)</p>
                    <p>
                      <strong>1. Objeto do FAPEM:</strong> Atua estritamente como plataforma de compartilhamento de vivências e integração espontânea. Fica expressamente vedada à plataforma a prestação de serviços psicológicos ou assistenciais em saúde mental.
                    </p>
                    <p>
                      <strong>2. Recomendação de Assistência Externa:</strong> No surgimento de intercorrências de cunho emergencial clínico ou de surto, o usuário deve buscar ajuda estatal imediata através do SAMU (192) ou CVV (188).
                    </p>
                    <p>
                      <strong>3. Isenção Extensiva e Irrevogabilidade:</strong> O aceite integral deste termo constitui renúncia expressa a ações de reparação médica ou clínica contra moderadores e desenvolvedores do aplicativo, mantendo os registros imutáveis e auditáveis.
                    </p>
                    <p className="text-[9px] italic border-t border-white/5 pt-1.5 mt-2 text-center text-gray-550">
                      🔒 Assinado digitalmente através de identificador local persistente. Modificação desativada.
                    </p>
                  </motion.div>
                )}
              </div>
            ) : (
              <div className="text-center py-2 text-red-400 text-[11px] font-bold">
                Aguardando assinatura dos termos regulatórios.
              </div>
            )}
          </div>
        </div>

        <button
          onClick={onLogout}
          className="w-full h-16 bg-red-500/10 text-[#ff4a5a] border border-red-500/20 rounded-2xl flex items-center justify-center space-x-3 font-medium hover:bg-red-500/15 active:scale-98 transition-all cursor-pointer"
          id="btn-logout"
        >
          <LogOut size={20} />
          <span>Sair da conta</span>
        </button>
      </div>

      <div className="px-6 pb-6 text-center">
        <p className="text-[10px] text-gray-600 font-light uppercase tracking-[0.2em]">FAPEM App v1.0.0</p>
      </div>

      <AvatarModal
        isOpen={isAvatarModalOpen}
        onClose={() => setIsAvatarModalOpen(false)}
        selectedId={user?.avatarId}
        onSelect={handleSelectAvatar}
      />

      {/* MODAL: EDITAR POST/COMENTÁRIO */}
      <AnimatePresence>
        {editingPost && (
          <div className="fixed inset-0 bg-black/75 backdrop-blur-sm flex items-center justify-center p-6 z-50 animate-in fade-in duration-200">
            <motion.div
              initial={{ scale: 0.95, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.95, opacity: 0, y: 20 }}
              className="bg-[#0a0f1f]/90 w-full max-w-sm rounded-[2rem] p-6 shadow-neon-purple shadow-xl border border-white/5 space-y-4"
            >
              <div className="flex justify-between items-center pb-2 border-b border-white/5">
                <div className="min-w-0 flex-1 mr-2">
                  <span className="text-[10px] text-purple-450 uppercase font-bold tracking-wider">Editando sua mensagem</span>
                  <h4 className="text-sm font-bold text-white truncate leading-tight mt-0.5">
                    {editingPost.title}
                  </h4>
                </div>
                <button
                  type="button"
                  onClick={() => setEditingPost(null)}
                  className="p-1 text-gray-500 hover:bg-white/10 hover:text-white rounded-full outline-none transition-transform active:scale-95 shrink-0 cursor-pointer"
                >
                  <X size={16} />
                </button>
              </div>

              <textarea
                value={editPostContent}
                onChange={(e) => setEditPostContent(e.target.value)}
                className="w-full text-xs text-white bg-[#12182b] border border-white/15 focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/50 rounded-2xl p-4 h-32 focus:outline-none resize-none leading-relaxed font-sans"
                placeholder="Insira a nova mensagem..."
                maxLength={1000}
              />

              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => setEditingPost(null)}
                  className="flex-1 py-3 bg-white/5 hover:bg-white/10 text-white text-xs font-bold rounded-2xl transition-all cursor-pointer outline-none border border-white/5"
                >
                  Cancelar
                </button>
                <button
                  type="button"
                  onClick={handleSavePostEdit}
                  disabled={!editPostContent.trim()}
                  className="flex-1 py-3 bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white text-xs font-bold rounded-2xl transition-all shadow-neon-purple active:scale-98 cursor-pointer outline-none"
                >
                  Salvar
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: CONFIRMAÇÃO E ESCOLHA DE DELEÇÃO DE TÓPICO */}
      <AnimatePresence>
        {topicToDelete && (
          <div className="fixed inset-0 bg-black/75 backdrop-blur-sm flex items-center justify-center p-6 z-50 animate-in fade-in duration-200">
            <motion.div
              initial={{ scale: 0.95, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.95, opacity: 0, y: 20 }}
              className="bg-[#0a0f1f]/90 w-full max-w-sm rounded-[2rem] p-6 shadow-neon-purple shadow-xl border border-white/5 space-y-4"
            >
              <div className="text-center space-y-1.5">
                <div className="w-12 h-12 bg-red-500/10 text-red-400 rounded-full flex items-center justify-center mx-auto text-xl mb-1 border border-red-500/20">
                  ⚠️
                </div>
                <h4 className="text-sm font-bold text-white leading-tight px-1 text-center">
                  Como deseja excluir o seu tópico?
                </h4>
                <p className="text-[11.5px] text-gray-400 leading-normal font-light">
                  "<strong>{topicToDelete.title}</strong>" possui respostas e discussões ativas. Grandes redes oferecem suporte ético de exclusão. Escolha a sua opção:
                </p>
              </div>

              <div className="space-y-2">
                <button
                  type="button"
                  onClick={() => handleScheduleTopicDeletion(topicToDelete.id)}
                  className="w-full text-left p-3.5 bg-amber-500/10 hover:bg-amber-500/15 cursor-pointer border border-amber-500/20 rounded-2xl transition-all flex items-start gap-2.5 outline-none font-sans"
                >
                  <span className="text-amber-400 pt-0.5 text-sm">📅</span>
                  <div>
                    <span className="text-xs font-bold text-amber-300 block">Agendar Exclusão (Recomendado)</span>
                    <span className="text-[10px] text-amber-400 font-light block leading-tight mt-0.5">
                      Suspende novas respostas, avisa os participantes e apaga permanentemente tudo em 24h.
                    </span>
                  </div>
                </button>

                <button
                  type="button"
                  onClick={() => handleImmediateTopicDeletion(topicToDelete.id)}
                  className="w-full text-left p-3.5 bg-red-500/10 hover:bg-red-500/15 cursor-pointer border border-red-500/20 rounded-2xl transition-all flex items-start gap-2.5 outline-none font-sans"
                >
                  <span className="text-red-400 pt-0.5 text-sm">🗑️</span>
                  <div>
                    <span className="text-xs font-bold text-red-300 block">Deleção Completa Imediata</span>
                    <span className="text-[10px] text-red-450 font-light block leading-tight mt-0.5">
                      Apaga imediatamente e permanentemente o tópico e todas as respostas do sistema de forma irreversível.
                    </span>
                  </div>
                </button>
              </div>

              <button
                type="button"
                onClick={() => setTopicToDelete(null)}
                className="w-full py-3 bg-white/5 hover:bg-white/10 text-white text-xs font-bold rounded-2xl transition-all cursor-pointer outline-none mt-2 border border-white/5"
              >
                Voltar / Cancelar
              </button>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: EDITAR SALA PERSONALIZADA (PREMIUM) */}
      <AnimatePresence>
        {editingRoom && (
          <div className="fixed inset-0 bg-black/75 backdrop-blur-sm flex items-center justify-center p-6 z-50 animate-in fade-in duration-200">
            <motion.div
              initial={{ scale: 0.95, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.95, opacity: 0, y: 20 }}
              className="bg-[#0a0f1f]/90 w-full max-w-sm rounded-[2rem] p-6 shadow-neon-blue shadow-xl border border-white/5 space-y-4"
            >
              <div className="flex justify-between items-center pb-2 border-b border-white/5">
                <div>
                  <span className="text-[10px] text-cyan-400 uppercase font-bold tracking-wider">Edição de Sala Premium</span>
                  <h4 className="text-sm font-bold text-white truncate leading-tight mt-0.5">
                    Modificar Configurações
                  </h4>
                </div>
                <button
                  type="button"
                  onClick={() => setEditingRoom(null)}
                  className="p-1 text-gray-500 hover:bg-white/10 hover:text-white rounded-full outline-none transition-transform active:scale-90 cursor-pointer"
                >
                  <X size={16} />
                </button>
              </div>

              <div className="space-y-3">
                <div className="space-y-1">
                  <label className="text-[10px] uppercase font-bold text-gray-500 pl-1 font-sans">Nome da Sala</label>
                  <input
                    type="text"
                    value={editRoomName}
                    onChange={(e) => setEditRoomName(e.target.value)}
                    className="w-full text-xs text-white bg-[#12182b] border border-white/15 focus:border-cyan-500/50 rounded-xl px-3 py-2.5 focus:outline-none"
                    placeholder="Nome marcante e acolhedor..."
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] uppercase font-bold text-gray-500 pl-1 font-sans">Descrição</label>
                  <textarea
                    value={editRoomDesc}
                    onChange={(e) => setEditRoomDesc(e.target.value)}
                    className="w-full text-xs text-white bg-[#12182b] border border-white/15 focus:border-cyan-500/50 rounded-xl px-3 py-2.5 h-16 focus:outline-none resize-none"
                    placeholder="Explique o propósito deste espaço..."
                  />
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] uppercase font-bold text-gray-500 pl-1 font-sans">Tipo de Acesso</label>
                  <div className="flex bg-[#12182b] p-1 rounded-xl border border-white/5">
                    <button
                      type="button"
                      onClick={() => setEditRoomType('public')}
                      className={`flex-1 py-1.5 text-center text-[10px] font-bold rounded-lg transition-all cursor-pointer ${editRoomType === 'public'
                        ? 'bg-[#0a0f1f] text-emerald-400 border border-white/5 shadow-xs'
                        : 'text-gray-500'
                        }`}
                    >
                      🌐 Pública
                    </button>
                    <button
                      type="button"
                      onClick={() => setEditRoomType('vip')}
                      className={`flex-1 py-1.5 text-center text-[10px] font-bold rounded-lg transition-all cursor-pointer ${editRoomType === 'vip'
                        ? 'bg-[#0a0f1f] text-amber-405 border border-white/5 shadow-xs'
                        : 'text-gray-500'
                        }`}
                    >
                      🔒 Privada
                    </button>
                  </div>
                </div>
              </div>

              <div className="flex gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => setEditingRoom(null)}
                  className="flex-1 py-3 bg-white/5 hover:bg-white/10 text-white text-xs font-bold rounded-2xl transition-all cursor-pointer outline-none border border-white/5"
                >
                  Cancelar
                </button>
                <button
                  type="button"
                  onClick={handleSaveRoomEdit}
                  disabled={!editRoomName.trim() || !editRoomDesc.trim()}
                  className="flex-1 py-3 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white text-xs font-bold rounded-2xl transition-all shadow-neon-blue active:scale-98 cursor-pointer outline-none border border-white/5"
                >
                  Salvar
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
